#!/usr/bin/env python3
"""Generates the RGB point-cloud test samples shipped in each host test's Assets/PointClouds folder.

Both files carry per-point colour, but through the two channel layouts the loader understands:
  * rgb_cloud.ply  — Stanford PLY, ascii, separate `red`/`green`/`blue` (uchar) channels
  * rgb_cloud.pcd  — PCL PCD, ascii, packed `rgb` (float32 whose bit pattern is 0x00RRGGBB)

Shapes are chosen so that a *wrong* colour decode is obvious at a glance: the PLY is a cube whose six
faces are six different colours, the PCD is a helix sweeping through the colour wheel.
"""
import math
import os
import struct
import sys


def cube_faces(n=22, size=1.0):
    """Points spread over the six faces of a cube, one distinct colour per face."""
    half = size / 2.0
    faces = [
        ((1, 0, 0), (255, 40, 40)), ((-1, 0, 0), (40, 220, 60)),
        ((0, 1, 0), (60, 110, 255)), ((0, -1, 0), (255, 220, 50)),
        ((0, 0, 1), (240, 60, 220)), ((0, 0, -1), (50, 220, 220)),
    ]
    points = []
    for axis, rgb in faces:
        for i in range(n):
            for j in range(n):
                a = -half + size * (i + 0.5) / n
                b = -half + size * (j + 0.5) / n
                if axis == (1, 0, 0):
                    p = (half, a, b)
                elif axis == (-1, 0, 0):
                    p = (-half, a, b)
                elif axis == (0, 1, 0):
                    p = (a, half, b)
                elif axis == (0, -1, 0):
                    p = (a, -half, b)
                elif axis == (0, 0, 1):
                    p = (a, b, half)
                else:
                    p = (a, b, -half)
                points.append((p[0], p[1], p[2], rgb))
    return points


def hsv_to_rgb(h, s=1.0, v=1.0):
    i = int(h * 6.0)
    f = h * 6.0 - i
    p, q, t = v * (1 - s), v * (1 - f * s), v * (1 - (1 - f) * s)
    r, g, b = [(v, t, p), (q, v, p), (p, v, t), (p, q, v), (t, p, v), (v, p, q)][i % 6]
    return r, g, b


def helix(turns=10, per_turn=200, radius=0.45, height=1.6):
    """A helix whose colour sweeps the full hue circle from bottom to top."""
    total = turns * per_turn
    points = []
    for k in range(total):
        t = k / total
        ang = 2.0 * math.pi * turns * t
        r, g, b = hsv_to_rgb((t * 3.0) % 1.0)
        points.append((math.cos(ang) * radius, math.sin(ang) * radius, height * (t - 0.5),
                       (int(r * 255), int(g * 255), int(b * 255))))
    return points


def write_ply(path, points, comment):
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("ply\nformat ascii 1.0\n")
        f.write(f"comment {comment}\n")
        f.write(f"element vertex {len(points)}\n")
        for prop in ("float x", "float y", "float z", "uchar red", "uchar green", "uchar blue"):
            f.write(f"property {prop}\n")
        f.write("end_header\n")
        for x, y, z, (r, g, b) in points:
            f.write(f"{x:.4f} {y:.4f} {z:.4f} {r} {g} {b}\n")


def write_pcd(path, points, comment):
    packed = [struct.unpack("<f", struct.pack("<I", (r << 16) | (g << 8) | b))[0]
              for _, _, _, (r, g, b) in points]
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("# .PCD v0.7 - Point Cloud Data file format\n")
        f.write(f"# {comment}\n")
        f.write("VERSION 0.7\nFIELDS x y z rgb\nSIZE 4 4 4 4\nTYPE F F F F\nCOUNT 1 1 1 1\n")
        f.write(f"WIDTH {len(points)}\nHEIGHT 1\nVIEWPOINT 0 0 0 1 0 0 0\nPOINTS {len(points)}\nDATA ascii\n")
        for (x, y, z, _), rgb in zip(points, packed):
            f.write(f"{x:.4f} {y:.4f} {z:.4f} {rgb!r}\n")


def main():
    if len(sys.argv) < 2:
        raise SystemExit("usage: gencloud.py <PointClouds dir> [more dirs...]")
    for out_dir in sys.argv[1:]:
        os.makedirs(out_dir, exist_ok=True)
        write_ply(os.path.join(out_dir, "rgb_cloud.ply"), cube_faces(),
                  "colour cube: generated by docs/testing/tools/gencloud.py, red/green/blue channels")
        write_pcd(os.path.join(out_dir, "rgb_cloud.pcd"), helix(),
                  "colour helix: generated by docs/testing/tools/gencloud.py, packed rgb channel")
        print(f"wrote {out_dir}")


if __name__ == "__main__":
    main()
